<?php

$labels = array();
$labels['tabtitle'] = 'Getmail';
$labels['addconfig'] = 'Add config';
$labels['deleteconfig'] = 'Delete config';
$labels['configs'] = 'Getmail Configs';
$labels['confignotfound'] = 'Getmail config not found!';
$labels['saveingdata'] = 'Saving data ...';
$labels['configform'] = 'Getmail Config';
$labels['configdeleteconfirm'] = 'Do you really want to delete this Getmail config?';
$labels['successfullydeleted'] = 'The Getmail configuration was successfully removed';

$labels['configgeneral'] = 'General';
$labels['configactive'] = 'Enabled';
$labels['configname'] = 'Name';

$labels['configtype'] = 'Type';
$labels['configserver'] = 'Server';
$labels['confighost'] = 'Hostname';
$labels['configport'] = 'Port';
$labels['configssl'] = 'Use SSL';

$labels['configauth'] = 'Authentication';
$labels['configuser'] = "Username";
$labels['configpass'] = "Password";

$labels['configadvanced'] = 'Advanced';
$labels['configmailboxes'] = 'Mailboxes';
$labels['configdelete'] = 'Delete mails on success';
$labels['configonlynew'] = 'Retrieve only new mails';
$labels['configpoll'] = 'Poll interval (s)';
$labels['configheader'] = 'Add custom message header';
?>
