<?php

$labels = array();
$labels['tabtitle'] = 'Getmail';
$labels['addconfig'] = 'Add config';
$labels['deleteconfig'] = 'Delete config';
$labels['configs'] = 'Getmail Configs';
$labels['confignotfound'] = 'Getmail config not found!';
$labels['saveingdata'] = 'Saving data ...';
$labels['configform'] = 'Getmail Config';
$labels['configdeleteconfirm'] = 'Do you really want to delete this Getmail config?';

$labels['configgeneral'] = 'General';
$labels['configname'] = 'Name';
$labels['configtype'] = 'Type';

$labels['configserver'] = 'Server';
$labels['confighost'] = 'Hostname';
$labels['configport'] = 'Port';

$labels['configauth'] = 'Authentication';
$labels['configusername'] = "Username";
$labels['configpassword'] = "Password";

?>
